### PR TITLE
Libscotch7.0.5

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@Kabbone sry for pinging you here but I do not know how to debug the test errors. Maybe you have an idea.

**Comment by Kabbone** [comment]
you build scotch INT32 and PaStiX is default INT64, if you want INT32 you need to pass a build flag "PASTIX_INT64=OFF"

**Comment by looooo** [comment]
Thanks foryour response @Kabbone. I think the scotch builds have int64 support. Also this feedstock seems to build fine. What is failing now are the ctests.

**Comment by Kabbone** [comment]
You see in the build of pastix that scotch 8 Byte test of cmake is failing and 4 Byte successful. Or did I look at the wrong build?

**Comment by looooo** [comment]
Ah thanks, yes true, so it's still the same issue.

**Pull request merged**
